[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(\n    \.git\n  | \.mypy_cache\n  | \.pytest_cache\n  | \.venv\n  | build\n  | dist\n)/
'''

[tool.isort]
profile = "django"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
skip_gitignore = true

[flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = ".git,__pycache__,venv,.venv,build,dist"
