[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(\n    \.git\n  | \.mypy_cache\n  | \.pytest_cache\n  | \.venv\n  | build\n  | dist\n)/
'''

[tool.isort]
profile = "black"

[flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = ".git,__pycache__,venv,.venv,build,dist"
