services:
  # Том сохраняет данные БД, поэтому пароль из .env фиксируется при первом запуске
  db:
    image: postgres:15-alpine
    restart: always
    env_file: ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    env_file: ../.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      API_URL: ${API_URL}
    depends_on:
      - db
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8000/health/
      interval: 10s
      retries: 3
    volumes:
      - ../backend:/app
      - ../media:/app/media
    networks:
      - blog
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
      args:
        API_URL: ${API_URL}
    env_file: ../.env
    environment:
      NEXT_PUBLIC_API_BASE: ${API_URL}
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - blog
    ports:
      - "3000:3000"

volumes:
  postgres_data: {}

networks:
  blog: {}
