x-envfile: &envfile ../.env

services:
  # Том сохраняет данные БД, поэтому пароль из .env фиксируется при первом запуске
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: *envfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - blog

  backend:
    build: ../backend/Dockerfile.dev
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    env_file: *envfile
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - ../backend:/app
      - ../media:/app/media
    networks:
      - blog
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
      args:
        API_URL: ${API_URL}
    env_file: *envfile
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - blog
    ports:
      - "3000:3000"

volumes:
  postgres_data: {}

networks:
  blog: {}
