version: '3.9'

services:
  backend_test:
    build:
      context: ../backend
      dockerfile: Dockerfile.test
    container_name: blog_backend_test
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_test
      - DJANGO_SECRET_KEY=insecure-test-key-for-testing-only
      - DJANGO_DEBUG=True
      - DB_ENGINE=sqlite
    volumes:
      - ../backend:/app
      - coverage_data:/app/coverage_data
      - pip_cache:/root/.cache/pip
      - pytest_cache:/app/.pytest_cache
    # Команда для запуска тестов и сбора покрытия
    command: >
      bash -c "
        export PYTHONPATH=/app &&
        # Проверка и доустановка необходимых пакетов
        pip install django-ratelimit==3.0.0 --force-reinstall && 
        pip list | grep -E 'factory|pytest|django|coverage|ratelimit' &&
        echo 'Запуск тестов...' &&
        # Вначале запускаем только тесты моделей, так как они наиболее стабильные
        python -m pytest blog/tests/models/ -v &&
        # Затем тесты middleware, которые не зависят от сервисов и представлений
        python -m pytest blog/tests/middleware/ -v &&
        # Затем запускаем все тесты с измерением покрытия
        python -m pytest blog/tests/models/ blog/tests/middleware/ --cov=blog \
        --cov-report=xml:/app/coverage_data/coverage.xml \
        --cov-report=html:/app/coverage_data/html \
        --cov-report=term-missing
      "

volumes:
  coverage_data:
  pip_cache:
  pytest_cache:
