# Generated by Django 5.2 on 2025-05-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_contactmessage_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_text_for_search',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
