# Generated by Django 5.2 on 2025-05-07 19:48

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-first_published_at"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Основной контент"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(
                blank=True, verbose_name="Описание (для SEO и анонса)"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="first_published_at",
            field=models.DateTimeField(verbose_name="Дата первой публикации"),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликован"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="URL (слаг)"),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                related_name="posts", to="blog.tag", verbose_name="Теги"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
    ]
