# Generated by Django 5.2 on 2025-05-08 10:19

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_options_alter_post_body_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analyticsevent",
            options={
                "verbose_name": "Событие аналитики",
                "verbose_name_plural": "События аналитики",
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "verbose_name": "Сообщение (контакты)",
                "verbose_name_plural": "Сообщения (контакты)",
            },
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name": "Рейтинг", "verbose_name_plural": "Рейтинги"},
        ),
        migrations.AlterModelOptions(
            name="shortlink",
            options={
                "verbose_name": "Короткая ссылка",
                "verbose_name_plural": "Короткие ссылки",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        # migrations.AlterField(
        #     model_name='post',
        #     name='body',
        #     field=models.JSONField(blank=True, default=blog.models.get_default_tiptap_json, null=True, verbose_name='Основной контент (Tiptap JSON)'),
        # ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts/",
                validators=[blog.models.validate_webp],
                verbose_name="Изображение для анонса",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
    ]
