# Generated by Django 5.2 on 2025-05-08 10:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_analyticsevent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body_json",
            field=models.JSONField(
                blank=True,
                default=blog.models.get_default_tiptap_json_string,
                null=True,
                verbose_name="Новый контент (Tiptap JSON)",
            ),
        ),
    ]
