# Generated by Django 5.2 on 2025-05-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_migrate_body_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="body",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="body_json",
            new_name="body",
        ),
        migrations.AlterField(
            model_name="post",
            name="first_published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата первой публикации"
            ),
        ),
    ]
