# Generated by Django 5.2 on 2025-05-08 13:59

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_remove_post_body_json_alter_post_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.JSONField(
                blank=True,
                default=blog.models.get_default_tiptap_json_string,
                null=True,
                verbose_name="Основной контент (JSON)",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="sitemap_changefreq",
            field=models.CharField(
                choices=[
                    ("always", "Always"),
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("never", "Never"),
                ],
                default="weekly",
                max_length=10,
                verbose_name="Changefreq для sitemap",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="sitemap_priority",
            field=models.DecimalField(
                decimal_places=1,
                default=0.5,
                help_text="От 0.0 до 1.0",
                max_digits=2,
                verbose_name="Priority для sitemap",
            ),
        ),
    ]
