# Generated by Django 5.2 on 2025-05-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_image_alter_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
