# Generated by Django 5.2 on 2025-05-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_contactmessage_is_processed_contactmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='ip',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='path',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='referrer',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(help_text='Email адрес для обратной связи', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Флаг, показывающий, было ли сообщение обработано'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(help_text='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(help_text='Имя отправителя сообщения', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Тема сообщения, может быть сгенерирована автоматически', max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=8, unique=True),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['created_at', 'path'], name='blog_analyt_created_9aeea6_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['created_at', 'ip'], name='blog_analyt_created_8d0ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['post', 'created_at'], name='blog_rating_post_id_4f999d_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['post', 'score'], name='blog_rating_post_id_2244ea_idx'),
        ),
    ]
