- hosts: all
  become: yes
  vars_files:
    - group_vars/all/vault.yml
  roles:
    - common
    - security
    - monitoring
    - docker
    - postgresql
    - redis
    - nginx
    - supervisor
    - celery
    - app
    - backup
